import { WidgetConfig } from '../types/widget';

export function generateScriptableCode(widget: WidgetConfig): string {
  const { theme, weather, calendar, battery, clock, quote, type, size } = widget;

  return `// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: cyan; icon-glyph: mobile-alt;

/**
 * GlanceCraft Widget for iOS Scriptable
 * Type: ${type} | Size: ${size}
 * Generated by GlanceCraft Studio
 */

async function createWidget() {
  const widget = new ListWidget();
  
  // Background Styling
  ${theme.bgType === 'gradient' ? `
  const gradient = new LinearGradient();
  gradient.locations = [0, 1];
  gradient.colors = [
    new Color("${theme.gradientFrom}"),
    new Color("${theme.gradientTo}")
  ];
  widget.backgroundGradient = gradient;
  ` : theme.bgType === 'solid' ? `
  widget.backgroundColor = new Color("${theme.bgColor.startsWith('#') ? theme.bgColor : '#0f172a'}");
  ` : `
  // Frosted Glass Effect fallback tint
  widget.backgroundColor = new Color("#1e293b", 0.7);
  `}

  widget.setPadding(16, 16, 16, 16);

  ${type === 'weather_forecast' || type === 'hybrid_dash' ? `
  // Header: Location & Weather
  const headerStack = widget.addStack();
  headerStack.layoutHorizontally();

  const titleText = headerStack.addText("${weather.city}");
  titleText.font = Font.boldSystemFont(14);
  titleText.textColor = new Color("${theme.textColor.startsWith('#') ? theme.textColor : '#ffffff'}");

  headerStack.addSpacer();

  const tempText = headerStack.addText("${weather.temperature}°${weather.unit}");
  tempText.font = Font.boldSystemFont(14);
  tempText.textColor = new Color("${theme.accentColor}");

  widget.addSpacer(8);
  ` : ''}

  ${type === 'clock_dual' || type === 'hybrid_dash' ? `
  // Clock & Date
  const date = new Date();
  const dfTime = new DateFormatter();
  dfTime.dateFormat = "${clock.timeFormat === '12h' ? 'h:mm a' : 'HH:mm'}";
  
  const timeText = widget.addText(dfTime.string(date));
  timeText.font = Font.heavySystemFont(26);
  timeText.textColor = new Color("${theme.textColor.startsWith('#') ? theme.textColor : '#ffffff'}");

  const dfDate = new DateFormatter();
  dfDate.dateFormat = "EEEE, MMM d";
  const dateText = widget.addText(dfDate.string(date));
  dateText.font = Font.mediumSystemFont(12);
  dateText.textColor = new Color("${theme.subtextColor.startsWith('#') ? theme.subtextColor : '#94a3b8'}");
  ` : ''}

  ${type === 'calendar_events' || type === 'hybrid_dash' ? `
  widget.addSpacer(6);
  const eventStack = widget.addStack();
  eventStack.layoutHorizontally();
  
  const eventLabel = eventStack.addText("📅 ${calendar.nextEventTitle}");
  eventLabel.font = Font.systemFont(11);
  eventLabel.textColor = new Color("${theme.textColor.startsWith('#') ? theme.textColor : '#ffffff'}");
  ` : ''}

  ${type === 'battery_system' || type === 'hybrid_dash' ? `
  widget.addSpacer(6);
  const batteryStack = widget.addStack();
  batteryStack.layoutHorizontally();

  const batteryText = batteryStack.addText("⚡ Phone: " + Math.round(Device.batteryLevel() * 100) + "%");
  batteryText.font = Font.semiboldSystemFont(11);
  batteryText.textColor = new Color("${theme.accentColor}");
  ` : ''}

  ${type === 'quote_inspiration' ? `
  const quoteText = widget.addText('"${quote.quote}"');
  quoteText.font = Font.italicSystemFont(13);
  quoteText.textColor = new Color("${theme.textColor.startsWith('#') ? theme.textColor : '#ffffff'}");
  
  widget.addSpacer(4);
  const authorText = widget.addText("— ${quote.author}");
  authorText.font = Font.boldSystemFont(11);
  authorText.textColor = new Color("${theme.subtextColor.startsWith('#') ? theme.subtextColor : '#94a3b8'}");
  ` : ''}

  return widget;
}

const widget = await createWidget();
if (config.runsInWidget) {
  Script.setWidget(widget);
} else {
  widget.present${size === 'large' ? 'Large' : size === 'medium' ? 'Medium' : 'Small'}();
}
Script.complete();
`;
}

export function generateKwgtFormulas(widget: WidgetConfig): string {
  const { weather, clock, battery, theme } = widget;

  return `## KWGT (Kustom Widget) Formula Code
## Paste into Kustom Widget Maker (Android)

[Globals]
gv(bg_color)  = ${theme.bgColor.startsWith('#') ? theme.bgColor : '#0f172a'}
gv(accent)    = ${theme.accentColor}
gv(text_col)  = ${theme.textColor.startsWith('#') ? theme.textColor : '#ffffff'}

[Time & Date Overlap Group]
Primary Clock Text:
$df(${clock.timeFormat === '12h' ? 'hh:mm a' : 'HH:mm'})$

Date Kicker:
$df(EEEE, MMMM d)$

Secondary City Time (${clock.secondaryCity}):
$df(${clock.timeFormat === '12h' ? 'hh:mm a' : 'HH:mm'}, r${clock.secondaryOffset >= 0 ? '+' : ''}${clock.secondaryOffset}h)$

[Weather Element]
Temperature:
$wi(temp)$°

Weather Condition:
$wi(cond)$ - High: $wf(max, 0)$° / Low: $wf(min, 0)$°

Location:
$li(loc)$ (${weather.city})

[Battery Gauge]
Battery Percentage:
$bi(level)$%

Charging State:
$if(bi(charging) = 1, "⚡ Charging", "🔋 Discharging")$

[Corner Radius & Shape]
Corner Radius: ${theme.borderRadius}
Padding: 16dp
`;
}

export function generateWidgetsmithJson(widget: WidgetConfig): string {
  return JSON.stringify({
    glanceCraftVersion: '1.0',
    exportTimestamp: new Date().toISOString(),
    widgetMetadata: {
      name: widget.name,
      type: widget.type,
      size: widget.size,
    },
    appearance: {
      backgroundColor: widget.theme.bgColor,
      gradientStart: widget.theme.gradientFrom,
      gradientEnd: widget.theme.gradientTo,
      accentColor: widget.theme.accentColor,
      textColor: widget.theme.textColor,
      fontStyle: widget.theme.fontFamily,
      borderRadius: widget.theme.borderRadius,
      glassBlur: widget.theme.glassBlur,
    },
    dataPayload: {
      location: widget.weather.city,
      secondaryCity: widget.clock.secondaryCity,
      quoteText: widget.quote.quote,
      quoteAuthor: widget.quote.author,
    }
  }, null, 2);
}

export function generateHtmlSnippet(widget: WidgetConfig): string {
  const { theme, weather, calendar, clock, battery } = widget;

  return `<!-- Standalone GlanceCraft Widget Embed -->
<div style="
  width: ${widget.size === 'small' ? '160px' : '340px'};
  min-height: ${widget.size === 'large' ? '340px' : '160px'};
  border-radius: ${theme.borderRadius}px;
  background: ${theme.bgType === 'gradient' ? `linear-gradient(${theme.gradientAngle}deg, ${theme.gradientFrom}, ${theme.gradientTo})` : theme.bgColor};
  color: ${theme.textColor};
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  padding: 16px;
  box-shadow: 0 10px 25px rgba(0,0,0,0.2);
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  box-sizing: border-box;
">
  <div style="display: flex; justify-content: space-between; align-items: center;">
    <span style="font-size: 11px; text-transform: uppercase; font-weight: 600; color: ${theme.subtextColor};">
      ${weather.city}
    </span>
    <span style="font-size: 11px; font-weight: 700; color: ${theme.accentColor};">
      ${weather.temperature}°${weather.unit}
    </span>
  </div>

  <div style="margin: 8px 0;">
    <div style="font-size: 32px; font-weight: 800; letter-spacing: -0.5px;">
      10:30 <span style="font-size: 12px; font-weight: 600;">AM</span>
    </div>
    <div style="font-size: 12px; opacity: 0.8; margin-top: 2px;">
      ${calendar.nextEventTitle}
    </div>
  </div>

  <div style="font-size: 11px; display: flex; justify-content: space-between; border-top: 1px solid rgba(255,255,255,0.15); padding-top: 8px;">
    <span>⚡ Battery: ${battery.phoneLevel}%</span>
    <span style="color: ${theme.accentColor};">Active</span>
  </div>
</div>
`;
}
